"""PR-OS P02/T03 M13 Artifact Registry candidate."""

from .adapters import (
    AdaptationResult,
    P1LegacyAdapter,
    build_open_type_envelope,
    build_successor_envelope,
    find_fixture_files,
    read_frontmatter,
    register_adaptation,
)
from .errors import (
    AdapterError,
    AppendOnlyViolation,
    ArtifactConflictError,
    ConcurrentWriterError,
    ContractValidationError,
    CorruptRegistryError,
    EnvelopeValidationError,
    FrontmatterParseError,
    SandboxBoundaryViolation,
    TruncatedRegistryError,
    UnknownArtifactError,
)
from .p02_t04_m13_compatibility import (
    CompatibilityPolicy,
    build_compatibility_assessment,
)
from .p02_t04_m13_materialization import sha256_bytes
from .p02_t04_m13_products import (
    P02_T04_CONTRACT_REF,
    P02_T04_IMPLEMENTATION_VERSION,
    ArtifactProduct,
    artifact_ref,
    stable_identifier,
    unique_text,
)
from .registry_v2 import ArtifactRegistry
from .schema_v2 import (
    ENVELOPE_SCHEMA_VERSION,
    EVENT_SCHEMA_VERSION,
    build_envelope,
    canonical_json,
    content_hash_value,
    ledger_record_ref,
    legacy_artifact_id,
    lineage_status,
    new_artifact_id,
    parent_link,
    resolved_parent_links,
    sha256_file,
    unresolved_requirement,
    validate_envelope,
    validate_readable_envelope,
)
from .snapshots import (
    build_compatibility_policy_snapshot_envelope,
    build_registry_snapshot_envelope,
    verify_compatibility_policy_snapshot,
    verify_registry_snapshot,
)
from .knowledge_feedback_adapter import (
    make_knowledge_registration_preview,
    validate_knowledge_registration_preview,
)
from .routing_evidence_adapter import (
    make_routing_evidence_envelope_preview,
    validate_routing_evidence_envelope_preview,
)

__all__ = [
    "AdapterError",
    "AdaptationResult",
    "AppendOnlyViolation",
    "ArtifactConflictError",
    "ArtifactProduct",
    "ArtifactRegistry",
    "CompatibilityPolicy",
    "ConcurrentWriterError",
    "ContractValidationError",
    "CorruptRegistryError",
    "ENVELOPE_SCHEMA_VERSION",
    "EVENT_SCHEMA_VERSION",
    "EnvelopeValidationError",
    "FrontmatterParseError",
    "P1LegacyAdapter",
    "P02_T04_CONTRACT_REF",
    "P02_T04_IMPLEMENTATION_VERSION",
    "SandboxBoundaryViolation",
    "TruncatedRegistryError",
    "UnknownArtifactError",
    "build_envelope",
    "build_compatibility_policy_snapshot_envelope",
    "build_compatibility_assessment",
    "build_open_type_envelope",
    "build_registry_snapshot_envelope",
    "build_successor_envelope",
    "canonical_json",
    "content_hash_value",
    "find_fixture_files",
    "legacy_artifact_id",
    "ledger_record_ref",
    "lineage_status",
    "new_artifact_id",
    "parent_link",
    "read_frontmatter",
    "register_adaptation",
    "resolved_parent_links",
    "sha256_file",
    "sha256_bytes",
    "stable_identifier",
    "unresolved_requirement",
    "unique_text",
    "validate_envelope",
    "validate_readable_envelope",
    "verify_compatibility_policy_snapshot",
    "verify_registry_snapshot",
    "artifact_ref",
    "make_knowledge_registration_preview",
    "validate_knowledge_registration_preview",
    "make_routing_evidence_envelope_preview",
    "validate_routing_evidence_envelope_preview",
]
