"""P03/T05 M05 successor003 public API."""

from .canonical import (
    canonical_json_bytes,
    content_hash_matches,
    external_hash_is_valid,
    typed_payload_hash,
    with_content_hash,
)
from .core import (
    CONCEPT_ORDER,
    SOURCE_PROFILE,
    assess_comparability,
    build_opportunity_candidate,
    classify_tension,
    evidence_set_hash,
    extract_author_stated_gaps,
    finite_number_or_none,
    make_ignore_decision,
    make_anchor_resolution_receipt,
    make_pair_ledger,
    make_source_snapshot,
    make_trigger_scope_receipt,
    normalize_text,
    project_comparison_concepts,
    validate_ignore_decision,
    validate_anchor_resolution_receipt,
    validate_opportunity_candidate,
    validate_source_card,
    validate_source_snapshot,
    validate_trigger_scope_receipt,
)
from .errors import (
    CandidateRejected,
    ContractRejected,
    EvidenceRejected,
    OpportunityAnalysisError,
    SourceRejected,
)

__all__ = [
    "CONCEPT_ORDER",
    "SOURCE_PROFILE",
    "CandidateRejected",
    "ContractRejected",
    "EvidenceRejected",
    "OpportunityAnalysisError",
    "SourceRejected",
    "assess_comparability",
    "build_opportunity_candidate",
    "canonical_json_bytes",
    "classify_tension",
    "content_hash_matches",
    "evidence_set_hash",
    "external_hash_is_valid",
    "extract_author_stated_gaps",
    "finite_number_or_none",
    "make_ignore_decision",
    "make_anchor_resolution_receipt",
    "make_pair_ledger",
    "make_source_snapshot",
    "make_trigger_scope_receipt",
    "normalize_text",
    "project_comparison_concepts",
    "typed_payload_hash",
    "validate_ignore_decision",
    "validate_anchor_resolution_receipt",
    "validate_opportunity_candidate",
    "validate_source_card",
    "validate_source_snapshot",
    "validate_trigger_scope_receipt",
    "with_content_hash",
]
