from __future__ import annotations
from memorive_settings.task_scheduling import scheduled

from copy import deepcopy
from dataclasses import asdict, is_dataclass
from enum import Enum
import hashlib
import json
import os
from pathlib import Path
import pickle
import shutil
import threading
from typing import Any, Callable, Mapping
import uuid

from .contracts import (
    Core_NODE_IDS, DATA_NODE, node_ids_for,
    CoreArtifact,
    CoreExecutionContext,
    CoreExecutionResult,
)
from .model_bridge import CoreModelBridge
from memorive_settings.call_ledger import execution_checkpoint
from .capacity import context_pack_budget, describe_capacity


def _is_chroma_hnsw_read_failure(error: Exception) -> bool:
    message = str(error).casefold()
    return (
        error.__class__.__module__.startswith("chromadb")
        and (
            "hnsw segment reader" in message
            or "error loading hnsw index" in message
            or ("collection" in message and ("does not exist" in message or "not found" in message))
        )
    )
from .segmented_distill import CoreSegmentedDistiller
from .task_controls import TaskControlStore
from .scheduling import PIPELINE_LANES
from memorive_folder_management import (
    document_artifact_path,
    document_folder,
    load_folder_management_policy,
)
from memorive_source_language import (
    detect_source_language,
    normalize_source_language,
    validate_generated_language,
)


_EXECUTION_LOCK = threading.RLock()


def _jsonable(value: Any) -> Any:
    if is_dataclass(value):
        return {key: _jsonable(item) for key, item in asdict(value).items()}
    if isinstance(value, Enum):
        return value.value
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, Mapping):
        return {str(key): _jsonable(item) for key, item in value.items()}
    if isinstance(value, (list, tuple, set, frozenset)):
        return [_jsonable(item) for item in value]
    return value


def _canonical_bytes(value: Any) -> bytes:
    return json.dumps(
        _jsonable(value),
        ensure_ascii=False,
        allow_nan=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")


def _validate_context_pack_language(artifact: Mapping[str, Any], *, source_text: str, source_language: str) -> None:
    # Only exact built-in retrieval vocabulary is metadata. Preserve the saved
    # pack and its hash; source blocks and every other field remain checked.
    from retrieval.structured_context import _FACET_SPECS
    content = _jsonable(artifact)
    for facet in content.get("pack", {}).get("query_facets", []):
        spec = _FACET_SPECS.get(facet.get("id"))
        if spec and facet.get("query_terms") == list(spec["terms"]):
            facet["query_terms"] = []
    validate_generated_language(
        source_text=source_text,
        generated_text=_canonical_bytes(content).decode("utf-8"),
        source_language=source_language,
        artifact_name="ContextPack",
    )


def _validate_judgment_language(judgment: Mapping[str, Any], *, source_text: str, source_language: str) -> None:
    # debt.path is a local ledger locator generated by this application, not
    # model prose. A Chinese Windows directory must not invalidate an English
    # review. Keep the original locator in the saved artifact and validate all
    # remaining review content, including pending status and dispute text.
    content = deepcopy(judgment)
    if isinstance(content.get("debt"), dict):
        content["debt"].pop("path", None)
    validate_generated_language(
        source_text=source_text,
        generated_text=_canonical_bytes(content).decode("utf-8"),
        source_language=source_language,
        artifact_name="Judgment.json",
    )


def _validate_artifact_language(path: Path, *, artifact_kind: str, source_text: str, source_language: str) -> None:
    text = path.read_text(encoding="utf-8")
    if artifact_kind == "CORE_CONTEXT_PACK":
        _validate_context_pack_language(json.loads(text), source_text=source_text, source_language=source_language)
    elif artifact_kind == "CORE_JUDGMENT_REVIEW":
        _validate_judgment_language(json.loads(text), source_text=source_text, source_language=source_language)
    else:
        if artifact_kind == "CORE_CARD":
            # Omission tombstones retain the exact removed value, including old
            # application-generated warnings. Exempt only those two known
            # warning values at the audit metadata path. Scientific values,
            # quotes, reasons and all other prose still pass the source guard;
            # neither the Card bytes nor its historical evidence are rewritten.
            import re
            import yaml
            from evidence_extraction.card import DANGER_UNKNOWN_KD, DANGER_UNKNOWN_FIELD
            fences = list(re.finditer(r"(?m)^---[ \t]*\r?$", text))
            if len(fences) >= 2 and fences[0].start() == 0:
                content = yaml.safe_load(text[fences[0].end():fences[1].start()])
                if isinstance(content, dict):
                    for omission in content.get("omissions") or []:
                        removed = omission.get("removed_value") if isinstance(omission, dict) else None
                        if isinstance(removed, dict) and removed.get("danger") in (DANGER_UNKNOWN_KD, DANGER_UNKNOWN_FIELD):
                            removed["danger"] = "Legacy application verification warning (original preserved)."
                    text = _canonical_bytes(content).decode("utf-8") + text[fences[1].end():]
        validate_generated_language(
            source_text=source_text, generated_text=text,
            source_language=source_language, artifact_name=artifact_kind,
        )


def _atomic_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.parent / f".{path.name}.{os.getpid()}.{uuid.uuid4().hex}.tmp"
    with temporary.open("xb") as stream:
        stream.write(_canonical_bytes(value) + b"\n")
        stream.flush()
        os.fsync(stream.fileno())
    os.replace(temporary, path)


def _atomic_pickle(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.parent / f".{path.name}.{os.getpid()}.{uuid.uuid4().hex}.tmp"
    with temporary.open("xb") as stream:
        pickle.dump(value, stream, protocol=pickle.HIGHEST_PROTOCOL)
        stream.flush()
        os.fsync(stream.fileno())
    os.replace(temporary, path)


def _sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest().upper()


def default_analysis_question(source_name: str, source_language: str) -> str:
    """Return the Core analysis question in the document's source language."""

    language = normalize_source_language(source_language)
    synthetic = "synthetic_one_page_literature_test" in str(source_name).casefold()
    if language == "zh":
        if synthetic:
            return "这份合成文献报告了什么即时回忆差异？为什么该结果不能视为真实科学证据？"
        return "请概括该文献的主要研究问题、方法、结果与限制，并核对关键结论的证据锚点。"
    if language == "ja":
        if synthetic:
            return "この合成文献は即時再生のどのような差を報告し、なぜ実在する科学的証拠として扱えないのか。"
        return "この文献の主な研究課題、方法、結果、限界を要約し、主要な主張の証拠アンカーを確認してください。"
    if synthetic:
        return (
            "What immediate-recall difference does this synthetic paper report, and why "
            "must the result not be treated as real scientific evidence?"
        )
    return (
        "Summarize the paper's main research question, methods, results, and limitations, "
        "and verify the evidence anchors for its key claims."
    )


def _review_labels(source_language: str) -> dict[str, str]:
    language = normalize_source_language(source_language)
    return {
        "zh": {
            "title": "人工最终复核包",
            "input_sha": "输入 SHA256",
            "question": "问题",
            "model": "分析模型",
            "trace": "引文追溯",
            "rulings": "异源裁决数",
            "pending": "待人工处理",
            "draft": "分析草案",
            "boundary": "边界声明",
            "boundary_text": "自动化链路只生成建议、证据锚点与异源校核记录；不代替用户的最终科研判断。",
            "synthetic": "若输入明确标注为合成材料，其中数据不得视为真实科学证据。",
        },
        "en": {
            "title": "Human final review package",
            "input_sha": "Input SHA256",
            "question": "Question",
            "model": "Analysis model",
            "trace": "Citation trace",
            "rulings": "Cross-model rulings",
            "pending": "Items requiring human review",
            "draft": "Analysis draft",
            "boundary": "Boundary",
            "boundary_text": "The automated workflow provides suggestions, evidence anchors, and cross-model review records; it does not replace the user's final scientific judgment.",
            "synthetic": "When the input is explicitly synthetic, its data must not be treated as real scientific evidence.",
        },
        "ja": {
            "title": "人による最終確認パッケージ",
            "input_sha": "入力 SHA256",
            "question": "質問",
            "model": "分析モデル",
            "trace": "引用の追跡",
            "rulings": "異種モデルの判定数",
            "pending": "人による確認が必要な項目",
            "draft": "分析案",
            "boundary": "境界",
            "boundary_text": "自動処理は提案、証拠アンカー、異種モデルの確認記録のみを生成し、利用者の最終的な科学判断に代わるものではありません。",
            "synthetic": "入力が合成資料と明記されている場合、そのデータを実在する科学的証拠として扱ってはいけません。",
        },
    }.get(language, {"title":"Human final review package","input_sha":"Input SHA256","question":"Question","model":"Analysis model","trace":"Citation trace","rulings":"Cross-model rulings","pending":"Items requiring human review","draft":"Analysis draft","boundary":"Boundary","boundary_text":"Suggestions and evidence anchors do not replace scientific judgment.","synthetic":"Synthetic inputs are not real scientific evidence."})


def render_human_review(
    *,
    title: str,
    paper_id: str,
    source_sha256: str,
    question: str,
    analysis: Any,
    judgment: Mapping[str, Any],
    source_language: str,
    synthetic: bool,
) -> str:
    """Render the human-review artifact without changing the document language."""

    labels = _review_labels(source_language)
    disputes = [row for row in judgment.get("rulings", []) if row.get("agrees") is False]
    omissions = judgment.get("omissions") or []
    prior_review_qualifications = tuple(getattr(analysis, "review_limitations", ()) or ())
    lines = [
        f"# {labels['title']}: {title}",
        "",
        f"- paper_id: `{paper_id}`",
        f"- {labels['input_sha']}: `{source_sha256}`",
        f"- {labels['question']}: {question}",
        f"- {labels['model']}: `{analysis.analysis_model}`",
        f"- {labels['trace']}: {judgment.get('trace_resolved')}/{judgment.get('trace_total')}",
        f"- {labels['rulings']}: {len(judgment.get('rulings') or [])}",
        f"- {labels['pending']}: {len(judgment.get('deferred') or []) + len(disputes) + len(omissions) + len(prior_review_qualifications)}",
        "",
        f"## {labels['draft']}",
        "",
        analysis.render(language=source_language),
        "",
        f"## {labels['boundary']}",
        "",
        labels["boundary_text"],
    ]
    if judgment.get("execution_status") == "SKIPPED":
        notice = {
            "zh": "核对分析已按设置跳过；尚未核验分析结论，须人工审核。",
            "en": "Analysis cross-check was disabled. The analysis remains unverified and requires human review.",
            "ja": "設定により分析の照合をスキップしました。分析結果は未検証であり、人による確認が必要です。",
        }[source_language]
        lines.extend(["", notice])
    if disputes:
        heading = {"zh": "待核对的审核异议", "en": "Review findings requiring human attention", "ja": "人による確認が必要なレビュー指摘"}[source_language]
        lines.extend(["", "## " + heading, ""])
        for row in disputes:
            lines.append(f"- [{row.get('i')}] {row.get('conclusion', '')}")
            lines.extend("  - " + str(item.get("detail", "")) for item in row.get("disputes", []))
    if omissions:
        from .analysis_omission import omission_notice
        lines.append(omission_notice(omissions, source_language))
    if synthetic:
        lines.append(labels["synthetic"])
    lines.append("")
    return "\n".join(lines)


class CorePipelineExecutor:
    """Thin Desktop adapter over the already-tested Core production modules."""

    def __init__(
        self,
        *,
        validation_runner: Any,
        runtime_root: Path | str,
        task_control_store: TaskControlStore | None = None,
        interaction_sink: Any = None,
    ):
        self.validation_runner = validation_runner
        self.task_control_store = task_control_store
        self.interaction_sink = interaction_sink
        self.review_service = None
        self.runtime_root = Path(runtime_root).resolve(strict=False)
        self.folder_management_policy = load_folder_management_policy()
        self.sandbox_root = self.runtime_root / "sandbox"
        self.ops_root = self.runtime_root / "ops"
        self.chroma_root = self.runtime_root / "vector-store"
        self.chroma_dir = self.chroma_root / "chroma-sandbox-v2"
        for path in (self.sandbox_root, self.ops_root, self.chroma_dir):
            path.mkdir(parents=True, exist_ok=True)
        self._bind_environment()

        # Restart-unsafe Chroma must be isolated before any resumed workflow
        # opens the shared collection and pins its files on Windows.
        from document_processing.chroma_durability import ensure_chroma_writable

        self.chroma_startup_recovery = ensure_chroma_writable("sandbox")

    def _bind_environment(self) -> None:
        values = {
            "MEMORIVE_VAULT_ROOT": str(self.runtime_root / "vault-disabled"),
            "MEMORIVE_DOCUMENT_PROCESSING_VAULT_ROOT": str(self.runtime_root / "vault-disabled"),
            "MEMORIVE_DOCUMENT_PROCESSING_SANDBOX_ROOT": str(self.sandbox_root),
            "MEMORIVE_OPS_ROOT": str(self.ops_root),
            "MEMORIVE_DOCUMENT_PROCESSING_CHROMA_ROOT": str(self.chroma_root),
            "MEMORIVE_DOCUMENT_PROCESSING_SANDBOX_CHROMA_DIR": str(self.chroma_dir),
            "MEMORIVE_MODEL_GATEWAY_CACHE_DIR": str(self.ops_root / "model_gateway_cache"),
            "MEMORIVE_RUNTIME_LOG_LOG_DIR": str(self.ops_root / "runtime_log"),
            "MEMORIVE_EVIDENCE_REVIEW_REPORT_DIR": str(self.ops_root / "evidence_review_reports"),
            "MEMORIVE_EVIDENCE_REVIEW_REPAIR_DIR": str(self.ops_root / "evidence_review_repairs"),
            "MEMORIVE_EVIDENCE_REVIEW_JUDGMENT_DEBT_DIR": str(self.ops_root / "evidence_review_judgment_debt"),
            "MEMORIVE_KNOWLEDGE_ADMISSION_LOG_DIR": str(self.ops_root / "knowledge_admission"),
            "MEMORIVE_RETRIEVAL_RERANK_ENABLED": "false",
            "MEMORIVE_DOCUMENT_PROCESSING_OCR_VIA_MODEL_GATEWAY_READY": "false",
        }
        conflicts = {
            key: (os.environ.get(key), expected)
            for key, expected in values.items()
            if os.environ.get(key) not in {None, expected}
        }
        if conflicts:
            raise RuntimeError(f"Core_RUNTIME_ENVIRONMENT_CONFLICT:{sorted(conflicts)}")
        os.environ.update(values)

        # Core intentionally resolves its four roots when its config module is
        # imported.  The packaged desktop imports the Capabilities segmented adapter before
        # a user job starts, so that module can already exist by the time this
        # isolated runtime is constructed.  Keep the adopted Core functions and
        # update only their cached root values to the exact environment just bound.
        from document_processing import config as document_processing_config

        document_processing_config.VAULT_ROOT = Path(values["MEMORIVE_DOCUMENT_PROCESSING_VAULT_ROOT"])
        document_processing_config.OPS_ROOT = Path(values["MEMORIVE_OPS_ROOT"])
        document_processing_config.SANDBOX_ROOT = Path(values["MEMORIVE_DOCUMENT_PROCESSING_SANDBOX_ROOT"])
        document_processing_config.CHROMA_ROOT = Path(values["MEMORIVE_DOCUMENT_PROCESSING_CHROMA_ROOT"])

    @staticmethod
    def _resume_card(folder, stage_root, completed):
        seed_name = "05_admitted_card" if "05_CARD_ADMISSION" in completed else "03_card_seed"
        seed = stage_root / f"{seed_name}.md"
        if not seed.is_file():
            # Historical jobs predate job-local Card checkpoints.
            return CorePipelineExecutor._one(folder, "[Card]", ".md")
        binding_path = stage_root / f"{seed_name}_binding.json"
        binding = json.loads(binding_path.read_text(encoding="utf-8"))
        if _sha256_file(seed) != binding.get("sha256"):
            raise RuntimeError("CORE_CARD_CHECKPOINT_HASH_MISMATCH")
        name = CorePipelineExecutor._one(folder, "[CleanMD]", ".md").name.replace("[CleanMD]", "[Card]", 1)
        destination = stage_root / seed_name / name
        destination.parent.mkdir(parents=True, exist_ok=True)
        if not destination.exists():
            shutil.copy2(seed, destination)
        if _sha256_file(destination) != binding["sha256"]:
            raise RuntimeError("CORE_CARD_CHECKPOINT_COPY_MISMATCH")
        return destination

    @staticmethod
    def _card_distill_revision(folder, context, node):
        """Keep a job's new Card separate from the previously admitted revision."""
        source_files = [
            CorePipelineExecutor._one(folder, "[CleanMD]", ".md"),
            CorePipelineExecutor._one(folder, "[Chunks]", ".jsonl"),
        ]
        root = context.run_root / "core_stages" / "03_card_revision"
        root.mkdir(parents=True, exist_ok=True)
        binding = {
            "schema_version": "MemoCardDistillRevision-v1",
            "job_id": context.job_id,
            "source_sha256": context.source_sha256,
            "profile_kind": node.get("profile_kind"),
            "execution_profile": deepcopy(node.get("execution_profile")),
            "source_files": {p.name: _sha256_file(p) for p in source_files},
        }
        binding_path = root / "source_binding.json"
        if binding_path.is_file():
            if json.loads(binding_path.read_text(encoding="utf-8")) != binding:
                raise RuntimeError("CARD_DISTILL_REVISION_BINDING_CONFLICT")
        else:
            _atomic_json(binding_path, binding)
        for source in source_files:
            destination = root / source.name
            if not destination.exists():
                temporary = root / f".{source.name}.{uuid.uuid4().hex}.tmp"
                shutil.copy2(source, temporary)
                os.replace(temporary, destination)
            if _sha256_file(destination) != binding["source_files"][source.name]:
                raise RuntimeError("CARD_DISTILL_REVISION_SOURCE_CONFLICT")
        return root

    @staticmethod
    def _paper_id(context: CoreExecutionContext) -> str:
        # The product cannot truthfully invent Core's preferred
        # surname+year identity before bibliographic confirmation. Use a
        # stable neutral fallback and never leak phase/build identifiers into
        # user artifact names. A later confirmed rename must go through the
        # Core registry and durable binding migration.
        return f"DOC_{context.source_sha256[:16].upper()}"

    @staticmethod
    def _question(context: CoreExecutionContext, source_language: str) -> str:
        return default_analysis_question(context.source_name, source_language)

    def _paper_folder(self, paper_id: str, *, required: bool = True) -> Path | None:
        root = self.sandbox_root / "文献库"
        matches = (
            sorted(path for path in root.iterdir() if path.is_dir() and path.name.startswith(f"[{paper_id}]"))
            if root.is_dir()
            else []
        )
        if not matches and not required:
            return None
        if len(matches) != 1:
            raise RuntimeError(f"Core_PAPER_FOLDER_CARDINALITY:{paper_id}:{len(matches)}")
        return matches[0]

    @staticmethod
    def _one(folder: Path, prefix: str, suffix: str | None = None) -> Path:
        matches = [path for path in folder.iterdir() if path.is_file() and path.name.startswith(prefix)]
        if suffix is not None:
            matches = [path for path in matches if path.name.endswith(suffix)]
        if len(matches) != 1:
            raise RuntimeError(f"Core_ARTIFACT_CARDINALITY:{prefix}:{len(matches)}")
        return matches[0]

    def _load_chunks(self, folder: Path, paper_id: str) -> tuple[list[dict[str, Any]], dict[str, str]]:
        rows = []
        for line in self._one(folder, "[Chunks]", ".jsonl").read_text(encoding="utf-8").splitlines():
            if line.strip():
                row = json.loads(line)
                if row.get("paper_id") != paper_id or not row.get("chunk_id") or not row.get("text"):
                    raise RuntimeError("Core_CHUNK_CONTRACT_INVALID")
                rows.append(row)
        mapping = {row["chunk_id"]: row["text"] for row in rows}
        if not rows or len(mapping) != len(rows):
            raise RuntimeError("Core_CHUNK_SET_INVALID")
        return rows, mapping

    def _document_processing_complete(self, paper_id: str) -> bool:
        folder = self._paper_folder(paper_id, required=False)
        if folder is None:
            return False
        try:
            rows, _mapping = self._load_chunks(folder, paper_id)
            self._one(folder, "[CleanMD]", ".md")
            chunks_path = self._one(folder, "[Chunks]", ".jsonl")
            from document_processing.chroma_durability import (
                ERROR_CODE,
                inspect_chroma_restart_durability,
                recover_embedding_checkpoint,
            )

            checkpoint = recover_embedding_checkpoint(chunks_path, target="sandbox")
            if checkpoint.get("status") == "READY":
                return checkpoint.get("chunk_count") == len(rows)
            if inspect_chroma_restart_durability("sandbox").get("status") == ERROR_CODE:
                return False
            import chromadb
            from document_processing.config import COLLECTION

            client = chromadb.PersistentClient(path=str(self.chroma_dir))
            try:
                collection = client.get_collection(COLLECTION["sandbox"])
                vector_ids = list(collection.get(where={"paper_id": paper_id}).get("ids") or [])
            finally:
                client.close()
            return len(vector_ids) == len(rows) and set(vector_ids) == {row["chunk_id"] for row in rows}
        except Exception:
            return False

    def _document_processing_query_readiness(self, paper_id: str) -> dict[str, Any]:
        """Distinguish durable rows from a restart-unsafe or unreadable HNSW index.

        Chroma 1.5.9's Rust local backend can acknowledge every SQLite row and
        answer queries in the writer process while leaving only
        ``index_metadata.pickle`` on disk.  A later process then fails to load
        the HNSW segment.  Inspect the exact collection segment as well as the
        live API so node 02 does not silently claim restart-safe retrieval.
        """
        from document_processing.chroma_durability import (
            embedding_checkpoint_status,
            ensure_chroma_writable,
            inspect_chroma_restart_durability,
        )
        from document_processing.config import COLLECTION

        collection_name = COLLECTION["sandbox"]
        folder = self._paper_folder(paper_id)
        assert folder is not None
        chunks_path = self._one(folder, "[Chunks]", ".jsonl")
        checkpoint = embedding_checkpoint_status(chunks_path, target="sandbox")
        disk_state = inspect_chroma_restart_durability("sandbox")
        if checkpoint.get("status") == "READY":
            recovery = (
                ensure_chroma_writable("sandbox")
                if disk_state.get("status") == "CHROMA_HNSW_INDEX_NOT_RESTART_DURABLE"
                else {"action": "UNCHANGED"}
            )
            return {
                "status": "READY",
                "paper_id": paper_id,
                "storage_mode": "DURABLE_EMBEDDING_CHECKPOINT_WITH_DOCUMENT_SIDECAR",
                "checkpoint_source": checkpoint.get("source"),
                "chunk_count": checkpoint.get("chunk_count"),
                "chroma_restart_status": disk_state.get("status"),
                "chroma_recovery_action": recovery.get("action"),
                "chroma_recovery_receipt": recovery.get("receipt"),
            }
        if disk_state.get("status") == "CHROMA_HNSW_INDEX_NOT_RESTART_DURABLE":
            return {
                "status": "DEGRADED_SIDECAR_FALLBACK_REQUIRED",
                "paper_id": paper_id,
                "reason_code": "CHROMA_HNSW_INDEX_NOT_RESTART_DURABLE",
                "missing_index_files": disk_state.get("missing_index_files", []),
            }
        import chromadb
        client = chromadb.PersistentClient(path=str(self.chroma_dir))
        collection = client.get_collection(collection_name)
        try:
            sample = collection.peek(limit=1)
        except Exception as error:
            if not _is_chroma_hnsw_read_failure(error):
                raise
            return {
                "status": "DEGRADED_SIDECAR_FALLBACK_REQUIRED",
                "paper_id": paper_id,
                "reason_code": "CHROMA_HNSW_INDEX_UNREADABLE",
            }
        finally:
            client.close()
        return {
            "status": "READY",
            "paper_id": paper_id,
            "sample_count": len(sample.get("ids") or []),
        }

    def _document_processing_document_complete(self, paper_id: str) -> bool:
        """Verify the independent node-01 boundary (DocumentIngest–DocumentChunk only)."""
        folder = self._paper_folder(paper_id, required=False)
        if folder is None:
            return False
        try:
            rows, _mapping = self._load_chunks(folder, paper_id)
            self._one(folder, "[RawMD]", ".md")
            self._one(folder, "[CleanMD]", ".md")
            return bool(rows)
        except Exception:
            return False

    @staticmethod
    def _artifact(
        *, artifact_id: str, kind: str, path: Path, display_name: str
    ) -> CoreArtifact:
        return CoreArtifact(
            artifact_id=artifact_id,
            kind=kind,
            path=path,
            sha256=_sha256_file(path),
            display_name=display_name,
        )

    @staticmethod
    def _copy(source: Path, destination: Path) -> Path:
        execution_checkpoint()
        destination.parent.mkdir(parents=True, exist_ok=True)
        if destination.is_file() and _sha256_file(destination) == _sha256_file(source):
            return destination
        temporary = destination.parent / f".{destination.name}.{os.getpid()}.{uuid.uuid4().hex}.tmp"
        shutil.copy2(source, temporary)
        execution_checkpoint()
        os.replace(temporary, destination)
        return destination

    @scheduled('LITERATURE', pipeline=True)
    def execute(
        self,
        context: CoreExecutionContext,
        *,
        completed_node_ids: tuple[str, ...],
        on_node_completed: Callable[[str, int], None],
    ) -> CoreExecutionResult:
        # Roots are profile-wide and checked under a short binding lock. Model
        # routing is context-local; different papers may occupy different lanes.
        with _EXECUTION_LOCK:
            self._bind_environment()
        with PIPELINE_LANES.paper((str(self.runtime_root), context.source_sha256)):
            execution_checkpoint()
            completed = set(completed_node_ids)
            node_ids=node_ids_for(context.workflow_definition)
            paper_id = self._paper_id(context)
            title = Path(context.source_name).stem
            stage_root = context.run_root / "core_stages"
            stage_root.mkdir(parents=True, exist_ok=True)
            bridge = CoreModelBridge(
                workflow_config=context.workflow_config,
                validation_runner=self.validation_runner,
                evidence_root=context.run_root / "model_calls",
                node_override_provider=(
                    (
                        lambda node_id: self.task_control_store.overrides(context.job_id).get(
                            node_id, {}
                        )
                    )
                    if self.task_control_store is not None
                    else None
                ),
            )

            import model_gateway.gateway as gateway_module

            gateway_binding = gateway_module.gateway_scope(bridge)
            gateway_binding.__enter__()
            held_lanes = {}

            def release_lanes():
                for key, lock in list(held_lanes.items()):
                    PIPELINE_LANES.leave(key, lock)
                    held_lanes.pop(key)

            def mark(node_id: str) -> None:
                execution_checkpoint()
                if node_id in completed:
                    return
                on_node_completed(node_id, node_ids.index(node_id) + 1)
                completed.add(node_id)
                if node_id in held_lanes:
                    PIPELINE_LANES.leave(node_id, held_lanes.pop(node_id))

            def start(*node_ids: str) -> None:
                execution_checkpoint()
                release_lanes()
                from memorive_settings.task_scheduling import execution_activity
                pending = [node_id for node_id in node_ids if node_id not in completed]
                if not pending:
                    return
                # Claim each node only at its own execution boundary.
                execution_activity('WAITING', pending[0])
                for node_id in pending:
                    while True:
                        held_lanes[node_id] = PIPELINE_LANES.enter(node_id)
                        started = (self.task_control_store.mark_started(context.job_id, node_id,
                            pause_callback=lambda: execution_activity('PAUSED_BEFORE', node_id))
                            if self.task_control_store is not None else {'status':'PASS'})
                        if started['status'] != 'PAUSED':
                            break
                        release_lanes()
                        execution_checkpoint()
                bridge.active_node_id = pending[0]
                execution_activity('RUNNING', pending[0])

            try:
                if "01_DOCUMENT_INGEST" not in completed:
                    start("01_DOCUMENT_INGEST")
                    if not self._document_processing_document_complete(paper_id):
                        from document_processing import run_document_processing

                        result = run_document_processing(
                            context.source_path,
                            data_ownership="self",
                            doc_type="literature",
                            paper_id=paper_id,
                            title=title,
                            target="sandbox",
                        )
                        _atomic_json(stage_root / "01_document_processing.json", result)
                        if result.status != "completed":
                            raise RuntimeError(
                                f"DOCUMENT_PROCESSING_FAILED:{result.stopped_at}:{result.error_type}:{result.error_message}"
                            )
                    if not self._document_processing_document_complete(paper_id):
                        raise RuntimeError("DOCUMENT_PROCESSING_OUTPUT_VERIFICATION_FAILED")
                    if self.review_service is not None:
                        self.review_service.structure.prepare(context,self._paper_folder(paper_id))
                    mark("01_DOCUMENT_INGEST")

                if not self._document_processing_document_complete(paper_id):
                    raise RuntimeError("DOCUMENT_PROCESSING_CHECKPOINT_ARTIFACTS_MISSING")

                folder = self._paper_folder(paper_id)
                assert folder is not None
                if DATA_NODE in node_ids:
                    if self.review_service is None:raise RuntimeError('REVIEW_SERVICE_REQUIRED')
                    self.review_service.prepare_raw(context,self._one(folder,'[RawMD]','.md'))
                    if DATA_NODE not in completed:
                        start(DATA_NODE)
                        effective=context.workflow_config['nodes'][DATA_NODE].copy()
                        if self.task_control_store:effective.update(self.task_control_store.overrides(context.job_id).get(DATA_NODE,{}))
                        self.review_service.data(context,enabled=effective.get('enabled',True))
                        mark(DATA_NODE)
                    elif self.review_service.store.get(context.job_id)['data_state']=='WAITING_INPUT':
                        self.review_service.data(context,enabled=context.workflow_config['nodes'][DATA_NODE].get('enabled',True))
                source_rows, source_chunk_texts = self._load_chunks(folder, paper_id)
                source_text = "\n".join(source_chunk_texts.values())
                from memorive_language.source import describe
                source_language_evidence = describe(source_text)
                source_language = source_language_evidence['language']
                question = self._question(context, source_language)
                validate_generated_language(
                    source_text=source_text,
                    generated_text=question,
                    source_language=source_language,
                    artifact_name="Analysis question",
                )
                if "02_CHUNK_EMBEDDING" not in completed:
                    start("02_CHUNK_EMBEDDING")
                    if not self._document_processing_complete(paper_id):
                        from document_processing import embed_from_chunks

                        chunks_path = self._one(folder, "[Chunks]", ".jsonl")
                        result = embed_from_chunks(chunks_path, target="sandbox")
                        _atomic_json(stage_root / "02_chunk_embedding.json", result)
                        if result.status != "completed":
                            raise RuntimeError(
                                f"CHUNK_EMBEDDING_FAILED:{result.error_type}:{result.error_message}"
                            )
                    if not self._document_processing_complete(paper_id):
                        raise RuntimeError("CHUNK_EMBEDDING_OUTPUT_VERIFICATION_FAILED")
                    _atomic_json(
                        stage_root / "02_embedding_query_readiness.json",
                        self._document_processing_query_readiness(paper_id),
                    )
                    mark("02_CHUNK_EMBEDDING")

                folder = self._paper_folder(paper_id)
                assert folder is not None

                capabilities_evidence_root = context.run_root / "long_document_segmented_distill"
                capabilities_summary_path = capabilities_evidence_root / "segmented_distill_summary.json"
                capabilities_distill_metrics: dict[str, Any] = (
                    json.loads(capabilities_summary_path.read_text(encoding="utf-8"))
                    if capabilities_summary_path.is_file()
                    else {}
                )
                card_path = self._resume_card(folder, stage_root, completed) if "03_CARD_DISTILL" in completed else None
                if "03_CARD_DISTILL" not in completed:
                    start("03_CARD_DISTILL")
                    effective_workflow_config = (
                        self.task_control_store.effective_workflow_config(
                            context.job_id, context.workflow_config
                        )
                        if self.task_control_store is not None
                        else context.workflow_config
                    )
                    segmented_distiller = CoreSegmentedDistiller(
                        workflow_config=effective_workflow_config,
                        evidence_root=capabilities_evidence_root,
                    )
                    distill_folder = self._card_distill_revision(
                        folder, context,
                        effective_workflow_config.get("nodes", {}).get("03_CARD_DISTILL", {}),
                    )
                    result = segmented_distiller.distill(
                        distill_folder,
                        target="sandbox",
                        overwrite=False,
                    )
                    capabilities_distill_metrics = deepcopy(segmented_distiller.last_metrics)
                    _atomic_json(
                        stage_root / "03_distill.json",
                        {"core_result": result, "long_document": capabilities_distill_metrics},
                    )
                    if result.status != "completed" or not result.card_path:
                        raise RuntimeError(
                            f"Core_EVIDENCE_EXTRACTION_FAILED:{result.error_type}:{result.error_message}"
                        )
                    card_path = Path(result.card_path)
                    seed = stage_root / "03_card_seed.md"
                    if not seed.exists(): shutil.copy2(card_path, seed)
                    _atomic_json(stage_root / "03_card_seed_binding.json", {
                        "sha256": _sha256_file(seed), "source_sha256": context.source_sha256,
                        "node_id": "03_CARD_DISTILL", "job_id": context.job_id})
                    mark("03_CARD_DISTILL")
                assert card_path is not None

                if not {"04_CARD_CROSS_CHECK", "05_CARD_ADMISSION"}.issubset(completed):
                    start("04_CARD_CROSS_CHECK")
                    from .card_review import review_card_revision
                    seed = stage_root / "03_card_seed.md"
                    review_input = seed if seed.is_file() else card_path
                    # Keep the original Card basename for the core readers.
                    if seed.is_file():
                        named_seed = stage_root / card_path.name
                        if not named_seed.exists(): shutil.copy2(seed, named_seed)
                        review_input = named_seed
                    def before_admission():
                        mark("04_CARD_CROSS_CHECK")
                        start("05_CARD_ADMISSION")
                    card_path = review_card_revision(review_input, folder, stage_root,
                                                    before_publish=before_admission)
                    admitted_seed = stage_root / "05_admitted_card.md"
                    if not admitted_seed.exists():
                        shutil.copy2(card_path, admitted_seed)
                    if _sha256_file(admitted_seed) != _sha256_file(card_path):
                        raise RuntimeError("Core_ADMITTED_CARD_CHECKPOINT_CONFLICT")
                    _atomic_json(stage_root / "05_admitted_card_binding.json", {
                        "sha256": _sha256_file(admitted_seed), "source_sha256": context.source_sha256,
                        "node_id": "05_CARD_ADMISSION", "job_id": context.job_id})
                    mark("04_CARD_CROSS_CHECK")
                    mark("05_CARD_ADMISSION")

                pack_pickle = stage_root / "06_context_pack.pkl"
                if DATA_NODE in node_ids and self.review_service:
                    self.review_service.card_ready(context,card_path,source_rows=source_rows)
                pack_json = stage_root / "06_context_pack.json"
                if "06_CONTEXT_PACK" not in completed:
                    start("06_CONTEXT_PACK")
                    from retrieval import build_context_pack, retrieve_candidates, understand_query

                    understood = understand_query(question)
                    # Document analysis needs the admitted paper's methods,
                    # results, conclusions, and source qualifications.
                    rows, chunk_texts = self._load_chunks(folder, paper_id)
                    from retrieval.candidate_retrieval import _read_frontmatter
                    from retrieval.document_context import (
                        bind_document_card, document_candidates,
                        document_candidates_from_sidecar,
                    )
                    card_for_context = _read_frontmatter(card_path)
                    if not card_for_context:
                        raise RuntimeError('Core_CONTEXT_CARD_UNREADABLE')
                    card_for_context = bind_document_card(
                        card_for_context, paper_id,
                        hashlib.sha256(card_path.read_bytes()).hexdigest(),
                    )
                    try:
                        candidates = retrieve_candidates(
                            question, understood.strategy, target="sandbox",
                            paper_id=paper_id,
                        )
                    except Exception as retrieval_error:
                        if not _is_chroma_hnsw_read_failure(retrieval_error):
                            raise
                        candidates = document_candidates_from_sidecar(
                            rows, card_for_context, paper_id
                        )
                    else:
                        # Question top-k seeds priority; whole-document coverage
                        # then adds every eligible chunk from the admitted paper.
                        candidates = document_candidates(
                            candidates, rows, card_for_context
                        )
                    effective_workflow_config = (
                        self.task_control_store.effective_workflow_config(
                            context.job_id, context.workflow_config
                        )
                        if self.task_control_store is not None
                        else context.workflow_config
                    )
                    analysis_node = effective_workflow_config.get("nodes", {}).get(
                        "07_ANALYSIS", {}
                    )
                    capacity = describe_capacity(
                        profile_kind=analysis_node.get("profile_kind"),
                        execution_profile=analysis_node.get("execution_profile"),
                        node_requested_output_tokens=65_536,
                    )
                    # Reuse the existing estimator and actual rendered prompt;
                    # do not pre-deduct invented reasoning/margin constants.
                    from retrieval.context_pack import _cfg, _estimate_tokens
                    from research_analysis.analysis import build_payload
                    from types import SimpleNamespace

                    estimator = _cfg()
                    candidate_tokens = sum(
                        _estimate_tokens(row.text, estimator['token_ratio'],
                                         estimator['overhead_per_block'])
                        for row in candidates.candidates
                    )
                    from retrieval.review_qualifications import card_review_qualifications, render_review_context
                    review_text = render_review_context(card_review_qualifications(card_for_context, paper_id=paper_id))
                    candidate_tokens += _estimate_tokens(review_text, estimator['token_ratio'], 0) if review_text else 0
                    empty_payload = build_payload(SimpleNamespace(blocks=()), question,
                                                  output_language=source_language)
                    prompt_tokens = sum(
                        _estimate_tokens(row.get('content', ''), estimator['token_ratio'], 0)
                        for row in empty_payload.get('messages', ())
                    )
                    pack_budget = context_pack_budget(
                        capacity, prompt_reserve_tokens=prompt_tokens,
                        candidate_estimated_tokens=candidate_tokens,
                        prompt_measurement_source='ACTUAL_RENDERED_PROMPT_WITH_EXISTING_RETRIEVAL_ESTIMATOR',
                    )
                    from retrieval.structured_context import build_structured_context_pack
                    pack = build_structured_context_pack(
                        candidates, question, card=card_for_context, chunks=rows,
                        strategy=understood.strategy, retrieval_mode='single_paper_extraction',
                        token_hard_limit=pack_budget['token_hard_limit'],
                    )
                    rows, chunk_texts = self._load_chunks(folder, paper_id)
                    block_ids = [block.source.get("chunk_id") for block in pack.blocks]
                    if (
                        getattr(candidates, "scope_mode", None) != "paper_id"
                        or getattr(candidates, "scope_paper_id", None) != paper_id
                        or not block_ids
                        or len(set(block_ids)) != len(block_ids)
                        or any(chunk_id not in chunk_texts for chunk_id in block_ids)
                        or pack.estimated_tokens > pack.token_hard_limit
                    ):
                        raise RuntimeError("CORE_CONTEXT_PACK_CONTRACT_FAILED")
                    _atomic_pickle(pack_pickle, pack)
                    context_pack_artifact = {
                            "question": question,
                            "source_language": source_language,
                    "source_language_evidence": source_language_evidence,
                            "understanding": understood,
                            "candidates": candidates,
                            "pack": pack,
                            "summary": {
                                "chunk_count": len(rows),
                                "block_count": len(pack.blocks),
                                "estimated_tokens": pack.estimated_tokens,
                                "token_hard_limit": pack.token_hard_limit,
                                "paper_id": paper_id,
                                "chunk_ids": block_ids,
                                "embedding_profile_source_node_id": "02_CHUNK_EMBEDDING",
                                "capacity": capacity,
                                "pack_budget": pack_budget,
                                "truncated": pack.truncated,
                                "original_estimated_tokens": pack.original_estimated_tokens,
                                "retained_estimated_tokens": pack.estimated_tokens,
                                "dropped_evidence_block_count": pack.dropped_evidence_block_count,
                                "dropped_reason_counts": pack.dropped_reason_counts,
                            },
                        }
                    _validate_context_pack_language(
                        context_pack_artifact,
                        source_text=source_text,
                        source_language=source_language,
                    )
                    _atomic_json(pack_json, context_pack_artifact)
                    mark("06_CONTEXT_PACK")
                with pack_pickle.open("rb") as stream:
                    pack = pickle.load(stream)
                context_pack_summary = {
                    "truncated": bool(pack.truncated),
                    "original_estimated_tokens": int(
                        getattr(pack, "original_estimated_tokens", 0) or 0
                    ),
                    "retained_estimated_tokens": int(pack.estimated_tokens),
                    "token_budget": int(pack.token_hard_limit),
                    "retained_block_count": len(pack.blocks),
                    "dropped_evidence_block_count": int(
                        getattr(pack, "dropped_evidence_block_count", 0) or 0
                    ),
                    "dropped_reason_counts": deepcopy(
                        getattr(pack, "dropped_reason_counts", None) or {}
                    ),
                    "recovery_action": (
                        {
                            "zh": "若需要更多证据，请为 Analysis 选择更大上下文的模型后，从 Context Pack 重新执行。",
                            "en": "If more evidence is needed, select an Analysis model with a larger context and rerun from Context Pack.",
                            "ja": "追加の証拠が必要な場合は、より大きなコンテキストを持つ Analysis モデルを選び、Context Pack から再実行してください。",
                        }[source_language]
                        if pack.truncated
                        else None
                    ),
                }

                analysis_pickle = stage_root / "07_analysis.pkl"
                analysis_json = stage_root / "07_analysis.json"
                analysis_md = stage_root / "07_analysis.md"
                if "07_ANALYSIS" not in completed:
                    start("07_ANALYSIS")
                    from research_analysis import analyze

                    analysis = analyze(
                        pack,
                        question,
                        data_ownership="self",
                        output_language=source_language,
                    )
                    valid_ids = {block.source.get("chunk_id") for block in pack.blocks}
                    emitted_ids = [claim.source_id.get("chunk_id") for claim in analysis.literature_support]
                    if any(chunk_id not in valid_ids for chunk_id in emitted_ids):
                        raise RuntimeError("CORE_ANALYSIS_SOURCE_ID_INVALID")
                    rendered_analysis = analysis.render(language=source_language)
                    validate_generated_language(
                        source_text=source_text,
                        generated_text=_canonical_bytes(analysis).decode("utf-8"),
                        source_language=source_language,
                        artifact_name="Analysis.json",
                    )
                    validate_generated_language(
                        source_text=source_text,
                        generated_text=rendered_analysis,
                        source_language=source_language,
                        artifact_name="Analysis.md",
                    )
                    _atomic_pickle(analysis_pickle, analysis)
                    _atomic_json(analysis_json, analysis)
                    analysis_md.write_text(rendered_analysis, encoding="utf-8")
                    mark("07_ANALYSIS")
                with analysis_pickle.open("rb") as stream:
                    analysis = pickle.load(stream)
                if self.interaction_sink is not None:
                    execution_checkpoint()
                    # Separate observation receipt; failure never reruns a completed model call.
                    try:
                        observation=self.interaction_sink(context,analysis)
                    except Exception:
                        observation={"status":"OBSERVATION_DELIVERY_FAILED","model_retry_required":False}
                    if observation.get("status")!="DISABLED_BY_USER":
                        try:_atomic_json(stage_root / "research_interaction_receipt.json",observation)
                        except OSError:pass  # Observational persistence is not a model failure.
                validate_generated_language(
                    source_text=source_text,
                    generated_text=analysis.render(language=source_language),
                    source_language=source_language,
                    artifact_name="Analysis checkpoint",
                )

                judgment_json = stage_root / "08_judgment.json"
                if "08_JUDGMENT_CROSS_CHECK" not in completed:
                    start("08_JUDGMENT_CROSS_CHECK")
                    if not bridge.node_enabled("08_JUDGMENT_CROSS_CHECK"):
                        judgment = {
                            "node_id": "08_JUDGMENT_CROSS_CHECK",
                            "execution_status": "SKIPPED",
                            "verification_result": "NOT_ASSESSED",
                            "reason": "DISABLED_BY_WORKFLOW_OR_TASK",
                            "drives_knowledge_admission": False,
                            "trace_total": 0, "trace_resolved": 0,
                            "rulings": [],
                            "deferred": [{"reason": "NODE_DISABLED_HUMAN_REVIEW_REQUIRED"}],
                            "target": {"run_id": context.job_id, "paper_id": paper_id},
                        }
                    else:
                        from evidence_review import verify_research_analysis

                        _rows, chunk_texts = self._load_chunks(folder, paper_id)
                        judgment = verify_research_analysis(
                            analysis,
                            chunk_texts,
                            data_ownership="self",
                            target={
                                "kind": "research_analysis",
                                "run_id": context.job_id,
                                "paper_id": paper_id,
                                "question": question,
                                "analysis_model": analysis.analysis_model,
                            },
                            max_gpt=2,
                            candidate_resolver=bridge.select_judgment_candidates,
                            output_language=source_language,
                        )
                        if judgment.get("trace_resolved") != judgment.get("trace_total"):
                            raise RuntimeError("Core_JUDGMENT_TRACE_UNRESOLVED")
                        if judgment.get("drives_knowledge_admission") is not False:
                            raise RuntimeError("Core_JUDGMENT_BOUNDARY_INVALID")
                        _validate_judgment_language(
                            judgment,
                            source_text=source_text,
                            source_language=source_language,
                        )
                    _atomic_json(judgment_json, judgment)
                    mark("08_JUDGMENT_CROSS_CHECK")
                judgment = json.loads(judgment_json.read_text(encoding="utf-8"))

                if judgment.get("execution_status") != "SKIPPED":
                    from .analysis_revision import complete_analysis_revision
                    _rows, revision_chunks = self._load_chunks(folder, paper_id)
                    revision_root = stage_root / "08_analysis_revision"
                    analysis, judgment = complete_analysis_revision(
                        analysis, pack, judgment, revision_chunks, bridge=bridge,
                        evidence_root=revision_root, output_language=source_language,
                    )
                    if (revision_root / "completed.json").is_file():
                        # Original 07/08 artifacts remain immutable; downstream
                        # packaging receives the reviewed successor explicitly.
                        analysis_pickle = revision_root / "analysis.pkl"
                        analysis_json = revision_root / "analysis.json"
                        analysis_md = revision_root / "analysis.md"

                review_md = stage_root / "09_human_review.md"
                if "09_HUMAN_FINAL" not in completed:
                    start("09_HUMAN_FINAL")
                    review_text = render_human_review(
                        title=title,
                        paper_id=paper_id,
                        source_sha256=context.source_sha256,
                        question=question,
                        analysis=analysis,
                        judgment=judgment,
                        source_language=source_language,
                        synthetic=(
                            "synthetic_one_page_literature_test"
                            in context.source_name.casefold()
                        ),
                    )
                    validate_generated_language(
                        source_text=source_text,
                        generated_text=review_text,
                        source_language=source_language,
                        artifact_name="HumanReview.md",
                    )
                    review_md.write_text(review_text, encoding="utf-8")

                source_documents = [
                    path
                    for path in folder.iterdir()
                    if path.is_file()
                    and (path.name.startswith("[PDF]") or path.name.startswith("[Original]"))
                ]
                if len(source_documents) != 1:
                    raise RuntimeError(
                        f"CORE_SOURCE_DOCUMENT_CARDINALITY:{len(source_documents)}"
                    )
                source_document = source_documents[0]
                raw = self._one(folder, "[RawMD]", ".md")
                clean = self._one(folder, "[CleanMD]", ".md")
                chunks = self._one(folder, "[Chunks]", ".jsonl")
                source_document_text = raw.read_text(encoding="utf-8")
                managed_folder = document_folder(
                    context.artifact_root,
                    paper_id=paper_id,
                    title=title,
                )
                artifact_specs = (
                    (
                        "core-source-document",
                        "CORE_SOURCE_DOCUMENT",
                        source_document,
                        managed_folder / source_document.name,
                        "原始文献",
                    ),
                    (
                        "core-raw-document",
                        "CORE_RAW_DOCUMENT",
                        raw,
                        document_artifact_path(
                            context.artifact_root,
                            artifact_kind="RawMD",
                            paper_id=paper_id,
                            title=title,
                        ),
                        "原始转换文档",
                    ),
                    (
                        "core-clean-document",
                        "CORE_CLEAN_DOCUMENT",
                        clean,
                        document_artifact_path(
                            context.artifact_root,
                            artifact_kind="CleanMD",
                            paper_id=paper_id,
                            title=title,
                        ),
                        "清洗文档",
                    ),
                    (
                        "core-chunks",
                        "CORE_CHUNKS",
                        chunks,
                        document_artifact_path(
                            context.artifact_root,
                            artifact_kind="Chunks",
                            paper_id=paper_id,
                            title=title,
                        ),
                        "Chunks",
                    ),
                    (
                        "core-card",
                        "CORE_CARD",
                        card_path,
                        document_artifact_path(
                            context.artifact_root,
                            artifact_kind="Card",
                            paper_id=paper_id,
                            title=title,
                        ),
                        "Card",
                    ),
                    (
                        "core-context-pack",
                        "CORE_CONTEXT_PACK",
                        pack_json,
                        document_artifact_path(
                            context.artifact_root,
                            artifact_kind="ContextPack",
                            paper_id=paper_id,
                            title=title,
                        ),
                        "Context Pack",
                    ),
                    (
                        "core-analysis",
                        "CORE_ANALYSIS",
                        analysis_md,
                        document_artifact_path(
                            context.artifact_root,
                            artifact_kind="Analysis",
                            paper_id=paper_id,
                            title=title,
                        ),
                        "Analysis",
                    ),
                    (
                        "core-judgment-review",
                        "CORE_JUDGMENT_REVIEW",
                        judgment_json,
                        document_artifact_path(
                            context.artifact_root,
                            artifact_kind="Judgment",
                            paper_id=paper_id,
                            title=title,
                        ),
                        "判断类异源校对",
                    ),
                    (
                        "core-human-review",
                        "CORE_HUMAN_REVIEW",
                        review_md,
                        document_artifact_path(
                            context.artifact_root,
                            artifact_kind="HumanReview",
                            paper_id=paper_id,
                            title=title,
                        ),
                        "人工最终复核包",
                    ),
                )
                # E10 candidates retain their own source-bound, verifiable bundle.
                structure_root=context.run_root/'structure-candidate'
                if (structure_root/'bundle.json').is_file():
                    from document_processing.document_structure.bundle import publication_specs
                    artifact_specs += publication_specs(structure_root,managed_folder/'structure')
                # The source-language rule is a persistence boundary, not only a
                # prompt hint.  Recheck every textual Core mainline artifact
                # immediately before it enters the product library.  RawMD is the
                # extracted source basis itself; all downstream text must not add
                # foreign Han narration that is absent from that basis.
                for (
                    _artifact_id,
                    artifact_kind,
                    source_path,
                    _target_path,
                    _display_name,
                ) in artifact_specs:
                    if artifact_kind in {"CORE_SOURCE_DOCUMENT","CORE_STRUCTURE_CANDIDATE"}:
                        continue
                    _validate_artifact_language(
                        source_path,
                        artifact_kind=artifact_kind,
                        source_text=source_document_text,
                        source_language=source_language,
                    )
                copied_artifacts = [
                    (
                        artifact_id,
                        artifact_kind,
                        self._copy(source_path, target_path),
                        display_name,
                    )
                    for artifact_id, artifact_kind, source_path, target_path, display_name
                    in artifact_specs
                ]
                manifest_path = document_artifact_path(
                    context.artifact_root,
                    artifact_kind="FolderManifest",
                    paper_id=paper_id,
                    title=title,
                )
                _atomic_json(
                    manifest_path,
                    {
                        "schema_version": "DesktopDocumentFolderManifest-v1",
                        "folder_policy": {
                            "schema_version": self.folder_management_policy.payload[
                                "schema_version"
                            ],
                            "revision": self.folder_management_policy.payload["revision"],
                            "sha256": self.folder_management_policy.sha256,
                        },
                        "job_id": context.job_id,
                        "paper_id": paper_id,
                        "title": title,
                        "layout": "ONE_PAPER_ONE_FOLDER_FLAT",
                        "files": [
                            {
                                "artifact_id": artifact_id,
                                "kind": artifact_kind,
                                "name": target_path.name,
                                "sha256": _sha256_file(target_path),
                                "bytes": target_path.stat().st_size,
                            }
                            for artifact_id, artifact_kind, target_path, _display_name
                            in copied_artifacts
                            if artifact_kind != "CORE_STRUCTURE_CANDIDATE"
                        ],
                        "legacy_files_deleted": 0,
                        "settings_files_touched": 0,
                    },
                )
                copied_artifacts.append(
                    (
                        "core-folder-manifest",
                        "CORE_FOLDER_MANIFEST",
                        manifest_path,
                        "文件夹清单",
                    )
                )
                artifacts = tuple(
                    self._artifact(
                        artifact_id=artifact_id,
                        kind=artifact_kind,
                        path=target_path,
                        display_name=display_name,
                    )
                    for artifact_id, artifact_kind, target_path, display_name
                    in copied_artifacts
                )
                metrics = {
                    "paper_id": paper_id,
                    "question": question,
                    "source_language": source_language,
                    "source_language_evidence": source_language_evidence,
                    "core_modules_reused": ["M01", "M02", "M03", "M04", "M06", "M08", "M09", "RUNTIME_LOG"],
                    "capabilities_successors_reused": ["LONG_DOCUMENT_SEGMENTED_DISTILLATION"],
                    "folder_management_policy": {
                        "schema_version": self.folder_management_policy.payload[
                            "schema_version"
                        ],
                        "revision": self.folder_management_policy.payload["revision"],
                        "sha256": self.folder_management_policy.sha256,
                    },
                    "long_document_distill": capabilities_distill_metrics,
                    "embedding_profile_ref": context.workflow_config["nodes"]["02_CHUNK_EMBEDDING"].get("profile_ref"),
                    "context_profile_source_node_id": context.workflow_config["nodes"]["06_CONTEXT_PACK"].get("profile_source_node_id"),
                    "context_pack": context_pack_summary,
                    "model_accounting": bridge.metrics(),
                    "human_final_state": "REVIEW_PACKAGE_READY_NO_AUTOMATED_SCIENTIFIC_VERDICT",
                }
                _atomic_json(context.run_root / "core_execution_summary.json", metrics)
                if "09_HUMAN_FINAL" not in completed:
                    mark("09_HUMAN_FINAL")
                return CoreExecutionResult(artifacts=artifacts, metrics=metrics)
            finally:
                release_lanes()
                gateway_binding.__exit__(None, None, None)


__all__ = ["CorePipelineExecutor"]
