"""Contract-bound Markdown renderer with hostile-text neutralization."""

from __future__ import annotations

import json
import re
import string
from collections import Counter
from pathlib import Path

from .canonical import FORBIDDEN_REPORT_PHRASES, forbidden_phrase, require_safe_text

MARKDOWN_META = frozenset(string.punctuation)
TEMPLATE_ROOT = Path(__file__).resolve().parent / "templates"
TOKEN_PATTERN = re.compile(r"{{([^{}]+)}}")

_TEMPLATE_CONTRACTS = {
    "daily": {
        "template_id": "PR-OS-P03-T02-M15-DAILY-REPORT",
        "template_revision": "r2.0",
        "sections": ("新增", "修改", "待审", "失败"),
        "placeholders": (
            "human_title",
            "attention_items",
            "overview_table",
            "coverage_summary",
            "detail_sections",
            "data_quality",
            "not_assessed",
            "audit_metadata",
        ),
    },
    "weekly": {
        "template_id": "PR-OS-P03-T02-M15-WEEKLY-REPORT",
        "template_revision": "r2.0",
        "sections": (
            "研究进展",
            "明确标记的重要变化",
            "未验证项",
            "明确来源的潜在张力",
            "风险与待办",
        ),
        "placeholders": (
            "human_title",
            "attention_items",
            "overview_table",
            "explicit_importance",
            "tension_summary",
            "coverage_summary",
            "detail_sections",
            "data_quality",
            "not_assessed",
            "audit_metadata",
        ),
    },
    "monthly": {
        "template_id": "PR-OS-P03-T02-M15-MONTHLY-REPORT",
        "template_revision": "r2.0",
        "sections": (
            "知识库结构变化",
            "明确记录的研究方向变化",
            "长期待办",
            "风险与未评估维度",
        ),
        "placeholders": (
            "human_title",
            "attention_items",
            "structural_summary",
            "direction_summary",
            "long_term_summary",
            "coverage_summary",
            "detail_sections",
            "data_quality",
            "not_assessed",
            "audit_metadata",
        ),
    },
}


def _plain(value: object, field: str) -> str:
    text = require_safe_text(str(value), field, allow_empty=True)
    hit = forbidden_phrase(text)
    if hit:
        raise ValueError(f"forbidden report phrase detected in {field}: {hit}")
    # Every dynamic value is plain escaped text. Static template headings and
    # bullets are the only Markdown syntax generated by this module.
    return "".join("\\" + char if char in MARKDOWN_META else char for char in text)


def _joined(values: list[object], field: str, *, empty: str = "N/A") -> str:
    return ", ".join(_plain(value, field) for value in values) or empty


def _line(item: dict) -> str:
    refs = _joined(item["artifact_or_ledger_refs"], "artifact_or_ledger_ref")
    evidence = _joined(item["evidence_refs"], "evidence_ref")
    return (
        f"- event {_plain(item['event_id'], 'event_id')} · source event "
        f"{_plain(item['source_event_ref'], 'source_event_ref')} · "
        f"{_plain(item['occurred_at'], 'occurred_at')} · {_plain(item['text'], 'text')} · "
        f"状态轴 {_plain(item['status_axis'], 'status_axis')}={_plain(item['status'], 'status')} · "
        f"对象 {refs} · 来源 {_plain(item['source_record_ref'], 'source_record_ref')} · 证据 {evidence}"
    )


def _load_template(kind: str) -> tuple[dict, str]:
    contract = _TEMPLATE_CONTRACTS.get(kind)
    if contract is None:
        raise ValueError(f"unsupported digest template kind: {kind}")
    sidecar_path = TEMPLATE_ROOT / f"{kind}.json"
    try:
        sidecar = json.loads(sidecar_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise ValueError(f"unable to load {kind} template sidecar") from exc
    expected_fields = {
        "template_id",
        "template_revision",
        "supersedes",
        "digest_kind",
        "human_title",
        "source_file",
        "front_purpose",
        "sections",
        "required_placeholders",
    }
    if not isinstance(sidecar, dict) or set(sidecar) != expected_fields:
        raise ValueError(f"{kind} template sidecar field contract mismatch")
    if (
        sidecar["template_id"] != contract["template_id"]
        or sidecar["template_revision"] != contract["template_revision"]
        or sidecar["supersedes"] != "r1.0"
        or sidecar["digest_kind"] != kind
        or sidecar["source_file"] != f"{kind}.md.tmpl"
        or sidecar["sections"] != list(contract["sections"])
        or sidecar["required_placeholders"] != list(contract["placeholders"])
        or not isinstance(sidecar["human_title"], str)
        or not sidecar["human_title"].strip()
        or not isinstance(sidecar["front_purpose"], str)
        or not sidecar["front_purpose"].strip()
    ):
        raise ValueError(f"{kind} template sidecar identity contract mismatch")
    template_path = TEMPLATE_ROOT / sidecar["source_file"]
    if template_path.parent.resolve() != TEMPLATE_ROOT.resolve():
        raise ValueError(f"{kind} template path escapes template root")
    try:
        template = template_path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        raise ValueError(f"unable to load {kind} Markdown template") from exc
    tokens = [match.strip() for match in TOKEN_PATTERN.findall(template)]
    expected_tokens = list(contract["placeholders"])
    if Counter(tokens) != Counter(expected_tokens) or any(
        count != 1 for count in Counter(tokens).values()
    ):
        raise ValueError(f"{kind} template placeholder contract mismatch")
    return sidecar, template


def _section_map(digest: dict, sidecar: dict) -> dict[str, list[dict]]:
    sections = digest.get("sections")
    if not isinstance(sections, list):
        raise ValueError("digest sections must be a list")
    titles = [section.get("title") for section in sections if isinstance(section, dict)]
    if titles != sidecar["sections"] or len(titles) != len(sections):
        raise ValueError("digest section contract does not match active template")
    result: dict[str, list[dict]] = {}
    for section in sections:
        items = section.get("items")
        if not isinstance(items, list):
            raise ValueError("digest section items must be a list")
        result[section["title"]] = items
    return result


def _event_summary(item: dict, section_title: str) -> str:
    return (
        f"- [{_plain(section_title, 'attention_section')}] event "
        f"{_plain(item['event_id'], 'attention_event_id')} · "
        f"{_plain(item['text'], 'attention_text')} · "
        f"{_plain(item['status_axis'], 'attention_status_axis')}="
        f"{_plain(item['status'], 'attention_status')} · 来源 "
        f"{_plain(item['source_record_ref'], 'attention_source_record_ref')}"
    )


def _unique_section_items(
    section_map: dict[str, list[dict]], section_titles: tuple[str, ...]
) -> list[tuple[str, dict]]:
    result: list[tuple[str, dict]] = []
    seen: dict[str, dict] = {}
    for title in section_titles:
        for item in section_map[title]:
            event_id = item.get("event_id")
            if not isinstance(event_id, str) or not event_id:
                raise ValueError("report item lacks event_id")
            prior = seen.get(event_id)
            if prior is not None:
                if prior != item:
                    raise ValueError(f"duplicate event payload mismatch: {event_id}")
                continue
            seen[event_id] = item
            result.append((title, item))
    return result


def _attention_items(
    digest: dict, section_map: dict[str, list[dict]], kind: str
) -> str:
    focus_sections = {
        "daily": ("失败", "待审"),
        "weekly": ("风险与待办", "未验证项"),
        "monthly": ("风险与未评估维度", "长期待办"),
    }[kind]
    lines: list[str] = []
    for conflict in digest["conflicts"]:
        lines.append(
            f"- [冲突] event {_plain(conflict['event_id'], 'attention_conflict_event_id')} · "
            "未自动择一 · 来源 "
            + _joined(conflict["source_record_refs"], "attention_conflict_source_ref")
        )
    for issue in digest["unparseable_events"]:
        if issue["blocking_status"] == "blocking":
            lines.append(
                f"- [阻断] {_plain(issue['issue_id'], 'attention_issue_id')} · "
                f"{_plain(issue['error_code'], 'attention_error_code')} · 来源 "
                f"{_plain(issue['source_record_ref'], 'attention_issue_source_ref')}"
            )
    lines.extend(
        _event_summary(item, title)
        for title, item in _unique_section_items(section_map, focus_sections)
    )
    if not lines:
        return "- 当前窗口没有来源支持的需优先处理记录。"
    visible_limit = 10
    if len(lines) <= visible_limit:
        return "\n".join(lines)
    hidden = len(lines) - visible_limit
    return "\n".join(lines[:visible_limit] + [f"- 另有 {hidden} 项，见详细记录。"])


def _overview_table(
    digest: dict, section_map: dict[str, list[dict]], sidecar: dict
) -> str:
    rows = ["| 类别 | 数量 |", "|---|---:|"]
    rows.extend(
        f"| {_plain(title, 'overview_section')} | {len(section_map[title])} |"
        for title in sidecar["sections"]
    )
    rows.extend(
        (
            f"| 迟到事件 | {len(digest['late_arrivals'])} |",
            f"| 冲突 | {len(digest['conflicts'])} |",
            f"| 不可解析 | {len(digest['unparseable_events'])} |",
        )
    )
    return "\n".join(rows)


def _coverage_summary(digest: dict) -> str:
    blocking_issues = sum(
        issue["blocking_status"] == "blocking"
        for issue in digest["unparseable_events"]
    )
    blocking_count = len(digest["conflicts"]) + blocking_issues
    readable = digest["report_status"] == "complete" and blocking_count == 0
    return "\n".join(
        (
            f"- report_status: {_plain(digest['report_status'], 'report_status')}",
            f"- authority_status: {_plain(digest['authority_status'], 'authority_status')}",
            f"- blocking_issue_count: {blocking_count}",
            f"- complete_readable: {'YES' if readable else 'NO'}",
            f"- NOT_ASSESSED_count: {len(digest['not_assessed_dimensions'])}",
        )
    )


def _section_summary(items: list[dict], title: str) -> str:
    if not items:
        return "- 无来源支持的记录。"
    return "\n".join(_event_summary(item, title) for item in items)


def _detail_sections(digest: dict) -> str:
    lines: list[str] = []
    seen: dict[str, tuple[str, dict]] = {}
    for index, section in enumerate(digest["sections"], 1):
        title = section["title"]
        lines.extend((f"### 1.{index} {_plain(title, 'section_title')}", ""))
        if not section["items"]:
            lines.append("- 无来源支持的记录。")
        for item in section["items"]:
            event_id = item["event_id"]
            prior = seen.get(event_id)
            if prior is None:
                seen[event_id] = (title, item)
                lines.append(_line(item))
            else:
                first_title, first_item = prior
                if first_item != item:
                    raise ValueError(f"duplicate event payload mismatch: {event_id}")
                lines.append(
                    f"- event {_plain(event_id, 'cross_reference_event_id')} → 交叉引用："
                    f"首次完整记录见「{_plain(first_title, 'cross_reference_section')}」。"
                )
        lines.append("")
    return "\n".join(lines).rstrip()


def _data_quality(digest: dict) -> str:
    lines = ["### 2.1 迟到事件", ""]
    if digest["late_arrivals"]:
        for item in digest["late_arrivals"]:
            lines.append(
                _line(item)
                + " · 原窗口 "
                + _plain(item["original_window_ref"], "original_window_ref")
                + " · 原截止 "
                + _plain(item["original_cutoff_at"], "original_cutoff_at")
            )
    else:
        lines.append("- 无。")
    lines.extend(("", "### 2.2 冲突", ""))
    if digest["conflicts"]:
        for conflict in digest["conflicts"]:
            lines.append(
                f"- {_plain(conflict['event_id'], 'conflict_event_id')} 存在内容冲突；"
                "未自动择一；来源 "
                + _joined(conflict["source_record_refs"], "conflict_source_ref")
            )
    else:
        lines.append("- 无。")
    lines.extend(("", "### 2.3 不可解析", ""))
    if digest["unparseable_events"]:
        for issue in digest["unparseable_events"]:
            lines.append(
                f"- {_plain(issue['issue_id'], 'issue_id')} · "
                f"{_plain(issue['error_code'], 'error_code')} · "
                f"{_plain(issue['blocking_status'], 'blocking_status')} · 来源 "
                f"{_plain(issue['source_record_ref'], 'issue_source_record_ref')}"
            )
    else:
        lines.append("- 无。")
    return "\n".join(lines)


def _not_assessed(digest: dict) -> str:
    if not digest["not_assessed_dimensions"]:
        return "- 无。"
    return "\n".join(
        f"- {_plain(value['dimension'], 'dimension')} = "
        f"{_plain(value.get('status', 'NOT_ASSESSED'), 'not_assessed_status')} · "
        f"{_plain(value['reason_code'], 'reason_code')}"
        for value in digest["not_assessed_dimensions"]
    )


def _audit_metadata(digest: dict, sidecar: dict) -> str:
    supersedes = digest.get("supersedes_digest_id") or "NONE"
    source_snapshots = _joined(
        digest.get("source_snapshot_refs", []), "source_snapshot_ref", empty="NONE"
    )
    return "\n".join(
        (
            f"- template_id: {_plain(sidecar['template_id'], 'template_id')}",
            f"- template_revision: {_plain(sidecar['template_revision'], 'template_revision')}",
            f"- digest_id: {_plain(digest['digest_id'], 'digest_id')}",
            f"- revision: {_plain(digest['revision'], 'revision')}",
            f"- window: {_plain(digest['window_start'], 'window_start')} 至 "
            f"{_plain(digest['window_end'], 'window_end')}（左闭右开）",
            f"- cutoff_at: {_plain(digest['cutoff_at'], 'cutoff_at')}",
            f"- generated_at: {_plain(digest.get('generated_at', 'NOT_RECORDED'), 'generated_at')}",
            f"- input_manifest_sha256: {_plain(digest['input_manifest_sha256'], 'input_manifest_sha256')}",
            f"- source_snapshot_refs: {source_snapshots}",
            f"- generator_version: {_plain(digest['generator_version'], 'generator_version')}",
            f"- supersedes_digest_id: {_plain(supersedes, 'supersedes_digest_id')}",
            f"- external_calls: {_plain(digest.get('external_calls', 'NOT_RECORDED'), 'external_calls')}",
            f"- external_tokens: {_plain(digest.get('external_tokens', 'NOT_RECORDED'), 'external_tokens')}",
            f"- cost_cny: {_plain(digest.get('cost_cny', 'NOT_RECORDED'), 'cost_cny')}",
            f"- production_mutations: {_plain(digest.get('production_mutations', 'NOT_RECORDED'), 'production_mutations')}",
            f"- production_activation: {_plain(digest.get('production_activation', 'NOT_RECORDED'), 'production_activation')}",
        )
    )


def _api_narrative_lines(rows: list[dict], label: str) -> str:
    if not rows:
        return "- 无来源支持的记录。"
    return "\n".join(
        f"- [API narrative · {_plain(label, 'api_narrative_label')}] "
        f"{_plain(row['text'], 'api_narrative_text')} · events "
        f"{_joined(row['event_ids'], 'api_narrative_event_id')}"
        for row in rows
    )


def _api_section_summary(narrative: dict, title: str) -> str:
    row = next(
        item
        for item in narrative["section_summaries"]
        if item["section_title"] == title
    )
    if row["text"] == "NONE":
        return "- 无来源支持的记录。"
    return _api_narrative_lines(
        [{"text": row["text"], "event_ids": row["event_ids"]}],
        title,
    )


def _api_audit_metadata(digest: dict, sidecar: dict, metadata: dict) -> str:
    base = _audit_metadata(digest, sidecar)
    return "\n".join(
        (
            base,
            "- narrative_external_calls: 1",
            f"- narrative_slot: {_plain(metadata['slot'], 'narrative_slot')}",
            f"- narrative_provider: {_plain(metadata['provider'], 'narrative_provider')}",
            f"- narrative_model: {_plain(metadata['model'], 'narrative_model')}",
            f"- narrative_response_sha256: {_plain(metadata['response_sha256'], 'narrative_response_sha256')}",
            f"- narrative_input_tokens: {_plain(metadata.get('input_tokens', 'NOT_RECORDED'), 'narrative_input_tokens')}",
            f"- narrative_output_tokens: {_plain(metadata.get('output_tokens', 'NOT_RECORDED'), 'narrative_output_tokens')}",
            f"- narrative_reasoning_tokens: {_plain(metadata.get('reasoning_tokens', 'NOT_RECORDED'), 'narrative_reasoning_tokens')}",
        )
    )


def _fill_template(template: str, values: dict[str, str], sidecar: dict) -> str:
    required = sidecar["required_placeholders"]
    if set(values) != set(required):
        raise ValueError("renderer placeholder value contract mismatch")
    rendered = template
    for key in required:
        rendered = rendered.replace("{{" + key + "}}", values[key])
    if "{{" in rendered or "}}" in rendered:
        raise ValueError("unresolved template placeholder")
    hit = forbidden_phrase(rendered)
    if hit:
        raise ValueError(f"forbidden report phrase detected after normalized scan: {hit}")
    return rendered.rstrip() + "\n"


def render_markdown(digest: dict) -> str:
    kind = digest.get("digest_kind")
    sidecar, template = _load_template(kind)
    section_map = _section_map(digest, sidecar)
    values = {
        "human_title": _plain(sidecar["human_title"], "human_title"),
        "attention_items": _attention_items(digest, section_map, kind),
        "coverage_summary": _coverage_summary(digest),
        "detail_sections": _detail_sections(digest),
        "data_quality": _data_quality(digest),
        "not_assessed": _not_assessed(digest),
        "audit_metadata": _audit_metadata(digest, sidecar),
    }
    if kind in {"daily", "weekly"}:
        values["overview_table"] = _overview_table(digest, section_map, sidecar)
    if kind == "weekly":
        values["explicit_importance"] = _section_summary(
            section_map["明确标记的重要变化"], "明确标记的重要变化"
        )
        values["tension_summary"] = _section_summary(
            section_map["明确来源的潜在张力"], "明确来源的潜在张力"
        )
    elif kind == "monthly":
        values["structural_summary"] = _section_summary(
            section_map["知识库结构变化"], "知识库结构变化"
        )
        values["direction_summary"] = _section_summary(
            section_map["明确记录的研究方向变化"], "明确记录的研究方向变化"
        )
        values["long_term_summary"] = _section_summary(
            section_map["长期待办"], "长期待办"
        )
    return _fill_template(template, values, sidecar)


def render_markdown_with_narrative(
    digest: dict,
    narrative: dict,
    metadata: dict,
) -> str:
    """Fill the active fixed template with a validated API front narrative.

    Detailed records, counts, quality state, NOT_ASSESSED dimensions and audit
    identity remain deterministic.  The model can only supply the concise
    front synthesis that was already validated against exact event IDs.
    """

    kind = digest.get("digest_kind")
    sidecar, template = _load_template(kind)
    section_map = _section_map(digest, sidecar)
    attention = [
        *_api_narrative_lines(narrative["period_summary"], "周期摘要").splitlines(),
        *_api_narrative_lines(narrative["priority_items"], "优先处理").splitlines(),
    ]
    values = {
        "human_title": _plain(sidecar["human_title"], "human_title"),
        "attention_items": "\n".join(attention),
        "coverage_summary": _coverage_summary(digest),
        "detail_sections": _detail_sections(digest),
        "data_quality": _data_quality(digest),
        "not_assessed": _not_assessed(digest),
        "audit_metadata": _api_audit_metadata(digest, sidecar, metadata),
    }
    if kind in {"daily", "weekly"}:
        values["overview_table"] = _overview_table(digest, section_map, sidecar)
    if kind == "weekly":
        values["explicit_importance"] = _api_section_summary(
            narrative, "明确标记的重要变化"
        )
        values["tension_summary"] = _api_section_summary(
            narrative, "明确来源的潜在张力"
        )
    elif kind == "monthly":
        values["structural_summary"] = _api_section_summary(
            narrative, "知识库结构变化"
        )
        values["direction_summary"] = _api_section_summary(
            narrative, "明确记录的研究方向变化"
        )
        values["long_term_summary"] = _api_section_summary(
            narrative, "长期待办"
        )
    return _fill_template(template, values, sidecar)
